spring:
    application:
        name: Review

    thymeleaf:
        cache: false
        enabled: true 
        prefix: 'classpath:/templates/'
        suffix: '.html'

    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:3306/reviewdb
        username: root
        password: reviewdb
    jpa:
        hibernate.ddl-auto: update
        generate-ddl: true
        show-sql: true
        
        
server:
    port: 8081

app:
    title: 'Avaliações'
    menu: 'Menu'

games:
    auth-url: https://id.twitch.tv/oauth2
    base-url: https://api.igdb.com/v4
    client-id: 5469gb9mrc6jqir6fxdl0ktmadbxsm
    secret: 7f9pausa2ojedok3eiivqwzq630xbs
    grant-type: client_credentials
    connect-timeout: 5000
    read-timeout: 10000
    